### ISSUE TITLE
configure label names in k8s adapter

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood_core#223]
We currently use these labels in our k8s pods, but some folks may want to use other labels. As an example instead of `app.kubernetes.io/name` they simply want to use `name` as that's standard in _their_ clusters.

```yaml
     job: <%= id %>
    app.kubernetes.io/name: <%= container.name %>
    app.kubernetes.io/managed-by: open-ondemand
    account: <%= script.accounting_id %>
```

This ticket is to allow for the configuration of label names in the adapters config so that folks unify the labels we supply with the labels they require in their own cluster.
