### ISSUE TITLE
make k8s configmap configuration a bit more intuative

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood_core#254]
With the addition of #251 hard coding the configmap mount path to `/ood` seems a bit clunky and makes configuration a bit counter intuitive in 

So this ticket is to get rid of this method and instead force the specification of the configmap mount path https://github.com/OSC/ood_core/blob/c6c833d343931521428d2f2bfddb8ed2c3468843/lib/ood_core/job/adapters/kubernetes/batch.rb#L115-L117. 

So a config like this would a configmap that would generate a file at the given directory for both init containers and the real container.
```yaml
configmap:
  files:
    - filename: "myfilename"
      mount_path: '/ood/myfile'
      data: |
        my file's data
```

This configuration would specify a different place to mount in the init containers.
```yaml
configmap:
  files:
    - filename: "myfilename"
      mount_path: '/ood/myfile'
      init_mount_path: '/init/my_init_file'  # specify a different init path
      data: |
        my file's data
```

I also wonder if we should allow for `init_mount_path: false`.

https://github.com/OSC/ood_core/blob/c6c833d343931521428d2f2bfddb8ed2c3468843/lib/ood_core/job/adapters/kubernetes/templates/pod.yml.erb#L109

It seems more intuitive to just instruct folks to use an init mount location that they'll ignore like `init_mount_path: '/wont_be_used'`.  Sort of like redirecting to /dev/null.  Instead of yet another configuration variant, simply ignore the init mount path.
