### ISSUE TITLE
Support GPU requests

### ISSUE THREAD

**Issue by treydock** [OSC/ood_core#263]
It would be useful to have ability to directly request GPUs via the various scheduler adapters.

SLURM:
```
--gpus-per-node=N
```

Torque:
```
-l nodes=X:ppn=Y:gpus=N
```

Kubernetes: https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/
```yaml
resources:
  limits:
    nvidia.com/gpu: 1
  requests:
    nvidia.com/gpu: 1
```
