### ISSUE TITLE
AKS support in kuberentes

### ISSUE THREAD

**Issue by johrstrom** [OSC/ood_core#747]
This ticket is to support AKS credential initialization in kuberentes.

**Comment by farassadek** [comment]
Hi Jeff

in "gems/ood_core-0.18.1/lib/ood_core/job/adapters/kubernetes/batch.rb"  we have 
- ```gcloud auth activate-service-account --key-file=#{cred_file}```
- ```gcloud container clusters get-credentials #{locale} #{cluster}```

 ```gcloud auth activate-service-account ``` is equivalent to  ```aws configure```
```aws configure``` to configure the the credentials on the server, it creates ~/.aws folder with two files, one for the credentials and another for other configuration like the region.

To get the credentials (given awscli is installed and ~/.aws folder exist: 
```aws configure get aws_access_key_id``` to get the access key given .aws exists 
```aws configure get aws_secret_access_key```
```aws configure get region```


for ```gcloud container clusters get-credentials #{locale} #{cluster}```


# Get the cluster name (assume one cluster available only).
```cluster_name=$(aws eks list-clusters | awk '{print $2}')```

# Get endpoint
```endpoint=$(aws eks describe-cluster --name $cluster_name  --query "cluster.endpoint")```

# Get the certificate
```certificate_data=$(aws eks describe-cluster --name $cluster_name  --query "cluster.certificateAuthority.data")```

```
mkdir -p ~/.kube
cat > ~/.kube/config << EOF

apiVersion: v1
clusters:
- cluster:
    server: $endpoint
    certificate-authority-data: $certificate_data
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - $cluster_name

EOF
```

``` cluster=$(kubectl get svc | grep -v NAME | awk '{print $1}') ```
```  aws eks get-token --cluster-name $cluster ```
