### ISSUE TITLE
Support job attr defaults in the cluster config

### ISSUE THREAD

**Issue by ericfranz** [OSC/ood_core#97]
Usage:

```
  job:
    adapter: "torque"
    host: "owens-batch.ten.osc.edu"
    lib: "/opt/torque/lib64"
    bin: "/opt/torque/bin"
    version: "6.0.1"
    defaults:
      reservation_id: "next.1234567"
```

Of course the question comes, if you set a default queue, and does that queue need to be used when checking the status, and with other commands? Maybe the individual adapters should be aware of which arguments are appropriate, so if defaults are provided they are used.
